import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import {
  ALL_STATUSES,
  compareVersionIds,
  isBusinessTask,
  isTerminalStatus,
  parseTaskIndexSnapshot,
  TaskIndex,
  type Task,
} from '../src/main/workbench/tasks/model.ts'
import { getUnmetDeps, isDepSatisfied, resolveWildcardDep } from '../src/main/workbench/tasks/deps.ts'
import { checkTransitionDeps } from '../src/main/workbench/tasks/statemachine.ts'
import { topologicalSort } from '../src/main/workbench/tasks/toposort.ts'

// Task 1.2 (M3) — dependency resolution + topological sort, TS port of
// forge-cli pkg/task/{deps.go,toposort.go}. Port authority = the Go source;
// the baseline in __fixtures__/baseline.json was generated by
// scripts/tasks-parity-gen against forge-cli @644321da over corpus.json plus
// real index.json snapshots (phase keys `5.gate`, T- system tasks, slug map
// keys ≠ bare IDs) and a dangling-blocker variant.
//
// SPEC CONTRADICTION (documented resolution): task AC-2 says rejected
// satisfies deps; the Go authority (deps.go satisfiedStatuses = completed +
// skipped; TestCheckTransitionDeps_RejectedDoesNotSatisfy) says it does not.
// Hard Rule #1 (行为差异一律以 Go 为准) wins — asserted below and locked by
// the parity baseline.
//
// Parity normalization: Go expands wildcard deps in map iteration order
// (unspecified), so unmet lists are compared as sorted multisets; every other
// output (topological order, cycles, missing, exact-dep unmet order) is
// deterministic and asserted strictly in the unit sections.

interface CorpusTaskEntry {
  readonly key: string
  readonly id: string
  readonly status: string
  readonly dependencies?: readonly string[]
  readonly sourceTaskID?: string
  readonly type?: string
}

interface CorpusDepCase {
  readonly name: string
  readonly tasks: readonly CorpusTaskEntry[]
  readonly target: string
  readonly rawDeps?: readonly string[]
}

interface CorpusTopoCase {
  readonly name: string
  readonly tasks: readonly CorpusTaskEntry[]
}

interface Corpus {
  readonly depCases: readonly CorpusDepCase[]
  readonly toposortCases: readonly CorpusTopoCase[]
}

interface BaselineCheckDeps {
  readonly unmet: readonly string[] | null
  readonly error?: string
}

interface BaselineDepCase {
  readonly name: string
  readonly checkDeps: BaselineCheckDeps | null
  readonly unmet: readonly string[] | null
}

interface BaselineTopoCase {
  readonly name: string
  readonly ordered: readonly string[] | null
  readonly cycles: readonly string[] | null
  readonly missing: readonly string[] | null
}

interface BaselineRealIndex extends BaselineTopoCase {
  readonly name: string
  readonly feature: string
  readonly unmetByTask: Readonly<Record<string, readonly string[] | null>>
  readonly checkDepsByTask: Readonly<Record<string, BaselineCheckDeps>>
}

interface Baseline {
  readonly forgeCliCommit: string
  readonly depCases: readonly BaselineDepCase[]
  readonly toposortCases: readonly BaselineTopoCase[]
  readonly realIndexes: readonly BaselineRealIndex[]
}

const fixturesUrl = new URL('../src/main/workbench/tasks/__fixtures__/', import.meta.url)
const corpus: Corpus = JSON.parse(readFileSync(new URL('corpus.json', fixturesUrl), 'utf8'))
const baseline: Baseline = JSON.parse(readFileSync(new URL('baseline.json', fixturesUrl), 'utf8'))

/** Build a TaskIndex from corpus entries (map key may differ from task ID). */
function corpusIndex(entries: readonly CorpusTaskEntry[]): TaskIndex {
  return new TaskIndex(entries.map(entry => [entry.key, entry as unknown as Task]))
}

/** Compact task literal (key defaults to the ID). */
function task(id: string, status: string, dependencies?: readonly string[], extra: Partial<Task> = {}): Task {
  return { id, status, dependencies, ...extra }
}

function index(...tasks: readonly Task[]): TaskIndex {
  return new TaskIndex(tasks.map(t => [t.id, t]))
}

const sorted = (v: readonly string[] | null | undefined): readonly string[] => [...(v ?? [])].sort()

// Tie normalization for ordered/cycles/missing: IDs that compare equal under
// the natural-order comparator (single-segment alphabetic IDs like m1's
// `fix-1`/`disc-2`/`T-review-doc` share rank (0, false)) are popped by the Go
// min-heap in MAP-ITERATION order — verified nondeterministic across
// regenerations of the Go baseline itself. Such tied neighbours therefore
// compare as an unordered run; every strictly-ordered position stays strict.
const tie = (a: string, b: string): boolean => !compareVersionIds(a, b) && !compareVersionIds(b, a)

function normalizeTies(list: readonly string[] | null | undefined): readonly string[] {
  const src = [...(list ?? [])]
  const out: string[] = []
  let run: string[] = []
  for (const id of src) {
    if (run.length === 0 || tie(run[run.length - 1] as string, id)) run.push(id)
    else {
      if (run.length > 1) run.sort()
      out.push(...run)
      run = [id]
    }
  }
  if (run.length > 1) run.sort()
  out.push(...run)
  return out
}

describe('task 1.2 model — statuses, ID dialect, natural order', () => {
  it('isTerminalStatus: completed/skipped/rejected only', () => {
    for (const status of ALL_STATUSES) {
      expect(isTerminalStatus(status), status).toBe(status === 'completed' || status === 'skipped' || status === 'rejected')
    }
  })

  it('isBusinessTask excludes T-/gate/summary IDs', () => {
    expect(isBusinessTask('1.2')).toBe(true)
    expect(isBusinessTask('1.2-statemachine-deps-port')).toBe(true)
    expect(isBusinessTask('1.gate')).toBe(false)
    expect(isBusinessTask('5.gate')).toBe(false)
    expect(isBusinessTask('1.summary')).toBe(false)
    expect(isBusinessTask('T-test-run')).toBe(false)
  })

  it('compareVersionIds: numeric segments numerically, numeric before alphabetic, gate before summary', () => {
    // strict ordering chain (each adjacent pair, plus the transitive ends)
    const chain = ['1', '1.1', '1.2', '1.10', '1.gate', '1.summary', '2', '10']
    for (let i = 0; i < chain.length - 1; i++) {
      expect(compareVersionIds(chain[i] as string, chain[i + 1] as string), `${chain[i]} < ${chain[i + 1]}`).toBe(true)
      expect(compareVersionIds(chain[i + 1] as string, chain[i] as string), `${chain[i + 1]} !< ${chain[i]}`).toBe(false)
    }
    expect(compareVersionIds('10', '9')).toBe(false)
    expect(compareVersionIds('9', '10')).toBe(true)
    expect(compareVersionIds('1.2', '1.2')).toBe(false)
    expect(compareVersionIds('1', '1.x')).toBe(true) // missing segment sorts before alphabetic
  })

  it('TaskIndex.byId: map key first, then ID fallback scan', () => {
    const idx = new TaskIndex([
      ['1.1-slug', task('1.1', 'completed')],
      ['1.2-slug', task('1.2', 'pending')],
    ])
    expect(idx.byId('1.1')?.status).toBe('completed') // ID fallback (no such key)
    expect(idx.byId('1.1-slug')?.id).toBe('1.1') // key hit
    expect(idx.byId('9.9')).toBeUndefined()
    // key precedence: key "2.1" wins over a task whose ID is "2.1"
    const prec = new TaskIndex([
      ['2.1', task('9.9', 'pending')],
      ['b', task('2.1', 'completed')],
    ])
    expect(prec.byId('2.1')?.id).toBe('9.9')
  })

  it('TaskIndex mutators: setTask + taskCount', () => {
    const idx = index(task('1.1', 'pending'))
    expect(idx.taskCount).toBe(1)
    idx.setTask('1.2-slug', task('1.2', 'blocked'))
    expect(idx.taskCount).toBe(2)
    expect(idx.byId('1.2')?.status).toBe('blocked')
  })

  it('parseTaskIndexSnapshot keeps snapshot fields verbatim', () => {
    const snap = { feature: 'f', tasks: { '1.1-s': { id: '1.1', status: 'blocked', dependencies: ['9.9'] } } }
    const idx = parseTaskIndexSnapshot(snap)
    expect(idx.byId('1.1')?.dependencies).toEqual(['9.9'])
    expect(idx.taskCount).toBe(1)
  })
})

describe('task 1.2 deps — terminal preconditions (Go authority)', () => {
  it('isDepSatisfied: completed and skipped only — rejected does NOT satisfy', () => {
    for (const status of ALL_STATUSES) {
      expect(isDepSatisfied(status), status).toBe(status === 'completed' || status === 'skipped')
    }
    expect(isDepSatisfied('rejected')).toBe(false) // Go TestCheckTransitionDeps_RejectedDoesNotSatisfy
  })

  it('rejected dependency stays unmet (SPEC CONTRADICTION resolved toward Go)', () => {
    const idx = index(task('1.1', 'rejected'), task('2.1', 'blocked', ['1.1']))
    expect(getUnmetDeps(idx, '2.1', ['1.1'])).toEqual(['1.1'])
  })

  it('suspended/blocked/pending/in_progress dependencies stay unmet', () => {
    const idx = index(
      task('2.1', 'blocked', ['7.1', '7.2', '7.4', '7.5']),
      task('7.1', 'pending'),
      task('7.2', 'in_progress'),
      task('7.4', 'blocked'),
      task('7.5', 'suspended'),
    )
    expect(getUnmetDeps(idx, '2.1', ['7.1', '7.2', '7.4', '7.5'])).toEqual(['7.1', '7.2', '7.4', '7.5'])
  })
})

describe('task 1.2 deps — resolveWildcardDep + getUnmetDeps', () => {
  it('exact deps return themselves, isWildcard=false (".xy" is not a wildcard)', () => {
    const idx = index(task('1.1-setup', 'completed'))
    expect(resolveWildcardDep(idx, '1.1-setup')).toEqual({ matches: ['1.1-setup'], isWildcard: false })
    expect(resolveWildcardDep(idx, '1.xy')).toEqual({ matches: ['1.xy'], isWildcard: false })
  })

  it('wildcard expands to business tasks only (gate/summary/T- excluded)', () => {
    const idx = index(
      task('1.1-setup', 'pending'),
      task('1.2-build', 'completed'),
      task('1.gate', 'pending'),
      task('1.summary', 'pending'),
      task('T-run', 'pending'),
      task('2.1-deploy', 'pending'),
    )
    const { matches, isWildcard } = resolveWildcardDep(idx, '1.x')
    expect(isWildcard).toBe(true)
    expect(sorted(matches)).toEqual(['1.1-setup', '1.2-build'])
  })

  it('wildcard with no match expands to nothing (not an unmet, not a missing)', () => {
    const idx = index(task('1.1-setup', 'pending'))
    expect(resolveWildcardDep(idx, '5.x')).toEqual({ matches: [], isWildcard: true })
    expect(getUnmetDeps(idx, '2.1', ['5.x'])).toBeNull()
  })

  it('exact-dep unmet preserves dependency order (deterministic path)', () => {
    const idx = index(task('1.1', 'completed'), task('1.2', 'pending'), task('1.3', 'skipped'), task('1.4', 'blocked'))
    expect(getUnmetDeps(idx, '2.1', ['1.4', '1.2', '1.1', '1.3'])).toEqual(['1.4', '1.2'])
    expect(getUnmetDeps(idx, '2.1', ['1.1', '1.3'])).toBeNull()
  })

  it('dangling exact dep is reported verbatim (no rewrite)', () => {
    const idx = index(task('1.1', 'completed'), task('2.1', 'blocked', ['1.1', '9.9']))
    expect(getUnmetDeps(idx, '2.1', ['1.1', '9.9'])).toEqual(['9.9'])
  })

  it('wildcard self-reference is excluded from unmet', () => {
    const idx = index(task('1.1-setup', 'pending'), task('1.2-build', 'pending'))
    expect(getUnmetDeps(idx, '1.1-setup', ['1.x'])).toEqual(['1.2-build'])
  })

  it('M2 dialect: deps carry bare IDs while map keys are slugs', () => {
    const idx = new TaskIndex([
      ['1.1-spike-a', task('1.1', 'completed')],
      ['1.2-port-b', task('1.2', 'pending')],
      ['2.1-consumer', task('2.1', 'blocked', ['1.1', '1.2'])],
    ])
    expect(getUnmetDeps(idx, '2.1', ['1.1', '1.2'])).toEqual(['1.2'])
  })
})

describe('task 1.2 deps — checkTransitionDeps (phase 2 + auto-unblock guard)', () => {
  it('all deps met, no active fix-task → unmet null', () => {
    const idx = index(task('1.1', 'completed'), task('1.2', 'completed'), task('2.1', 'blocked', ['1.1', '1.2']))
    expect(checkTransitionDeps(idx, '2.1')).toEqual({ unmet: null, error: null })
  })

  it('unmet deps pass through in order', () => {
    const idx = index(task('1.1', 'completed'), task('1.2', 'pending'), task('2.1', 'blocked', ['1.1', '1.2']))
    expect(checkTransitionDeps(idx, '2.1')).toEqual({ unmet: ['1.2'], error: null })
  })

  it('active fix-task blocks auto-unblock with the sentinel entry', () => {
    const idx = index(
      task('1.1', 'completed'),
      task('2.1', 'blocked', ['1.1'], { sourceTaskID: '1.1' }),
      task('T-fix-1', 'in_progress', undefined, { sourceTaskID: '2.1', type: 'coding.fix' }),
    )
    expect(checkTransitionDeps(idx, '2.1')).toEqual({ unmet: ['active fix-task exists'], error: null })
  })

  it('terminal fix-tasks (completed/rejected) no longer block', () => {
    const done = index(
      task('1.1', 'completed'),
      task('2.1', 'blocked', ['1.1']),
      task('T-fix-1', 'completed', undefined, { sourceTaskID: '2.1', type: 'coding.fix' }),
    )
    expect(checkTransitionDeps(done, '2.1')).toEqual({ unmet: null, error: null })
    const rejected = index(
      task('1.1', 'completed'),
      task('2.1', 'blocked', ['1.1']),
      task('T-fix-1', 'rejected', undefined, { sourceTaskID: '2.1', type: 'coding.fix' }),
    )
    expect(checkTransitionDeps(rejected, '2.1')).toEqual({ unmet: null, error: null })
  })

  it('fix-type variants: coding.fix.<surface> prefix and doc.fix both count', () => {
    const prefixed = index(
      task('1.1', 'completed'),
      task('2.1', 'blocked', ['1.1']),
      task('T-fixweb', 'pending', undefined, { sourceTaskID: '2.1', type: 'coding.fix.web' }),
    )
    expect(checkTransitionDeps(prefixed, '2.1').unmet).toEqual(['active fix-task exists'])
    const docfix = index(
      task('1.1', 'completed'),
      task('2.1', 'blocked', ['1.1']),
      task('T-docfix', 'pending', undefined, { sourceTaskID: '2.1', type: 'doc.fix' }),
    )
    expect(checkTransitionDeps(docfix, '2.1').unmet).toEqual(['active fix-task exists'])
    const nonFix = index(
      task('1.1', 'completed'),
      task('2.1', 'blocked', ['1.1']),
      task('T-other', 'pending', undefined, { sourceTaskID: '2.1', type: 'coding.feature' }),
    )
    expect(checkTransitionDeps(nonFix, '2.1').unmet).toBeNull()
  })

  it('fix-task targeting another task does not block this one', () => {
    const idx = index(
      task('1.1', 'completed'),
      task('2.1', 'blocked', ['1.1']),
      task('3.1', 'pending'),
      task('T-fix-2', 'in_progress', undefined, { sourceTaskID: '3.1', type: 'coding.fix' }),
    )
    expect(checkTransitionDeps(idx, '2.1')).toEqual({ unmet: null, error: null })
  })

  it('task not found yields the Go error message', () => {
    expect(checkTransitionDeps(new TaskIndex(), 'zzz')).toEqual({ unmet: null, error: 'task not found: zzz' })
  })

  it('key-precedence: lookup by key shadows a same-named ID', () => {
    const idx = new TaskIndex([
      ['2.1', task('9.9', 'pending')],
      ['b', task('2.1', 'completed')],
      ['c', task('3.1', 'blocked', ['2.1'])],
    ])
    expect(checkTransitionDeps(idx, '3.1').unmet).toEqual(['2.1'])
  })
})

describe('task 1.2 toposort — Kahn with natural-ID min-heap', () => {
  it('empty index', () => {
    const { ordered, cycles, missing } = topologicalSort(new TaskIndex())
    expect(ordered).toEqual([])
    expect(cycles).toEqual([])
    expect(missing).toEqual([])
  })

  it('same-level tasks sort by natural ID (10 after 2)', () => {
    const idx = index(task('3'), task('1'), task('2'), task('10'), task('1.1'))
    expect(topologicalSort(idx).ordered).toEqual(['1', '1.1', '2', '3', '10'])
  })

  it('M2 phase-key dialect: 1 < 1.1 < 1.2 < 1.gate < 1.summary < 2', () => {
    const idx = index(
      task('1'),
      task('1.1'),
      task('1.2'),
      task('1.gate'),
      task('1.summary'),
      task('2', 'pending', ['1.x']),
    )
    expect(topologicalSort(idx).ordered).toEqual(['1', '1.1', '1.2', '1.gate', '1.summary', '2'])
  })

  it('linear chain and diamond orders', () => {
    const chain = index(task('1'), task('2', 'pending', ['1']), task('3', 'pending', ['2']))
    expect(topologicalSort(chain).ordered).toEqual(['1', '2', '3'])
    const diamond = index(
      task('1'),
      task('2', 'pending', ['1']),
      task('3', 'pending', ['1']),
      task('4', 'pending', ['2', '3']),
    )
    expect(topologicalSort(diamond).ordered).toEqual(['1', '2', '3', '4'])
  })

  it('cycles: full cycle, self-reference, and wildcard self-edge', () => {
    const full = index(task('1', 'pending', ['3']), task('2', 'pending', ['1']), task('3', 'pending', ['2']))
    expect(topologicalSort(full)).toEqual({ ordered: [], cycles: ['1', '2', '3'], missing: [] })
    const self = index(task('1', 'pending', ['1']))
    expect(topologicalSort(self)).toEqual({ ordered: [], cycles: ['1'], missing: [] })
    // expandDeps keeps wildcard self-matches as edges (cycle detection),
    // unlike getUnmetDeps which excludes self.
    const wild = index(task('1.1', 'pending', ['1.x']), task('1.2'), task('2'))
    expect(topologicalSort(wild)).toEqual({ ordered: ['1.2', '2'], cycles: ['1.1'], missing: [] })
  })

  it('cycle members are reported alongside the healthy component', () => {
    const idx = index(
      task('1'),
      task('2', 'pending', ['1']),
      task('3', 'pending', ['4']),
      task('4', 'pending', ['3']),
    )
    expect(topologicalSort(idx)).toEqual({ ordered: ['1', '2'], cycles: ['3', '4'], missing: [] })
  })

  it('missing deps are collected and naturally sorted; the task itself still orders', () => {
    const idx = index(task('1', 'pending', ['99', '100']))
    expect(topologicalSort(idx)).toEqual({ ordered: ['1'], cycles: [], missing: ['99', '100'] })
  })

  it('unmatched wildcard is not a missing dep', () => {
    const idx = index(task('2', 'pending', ['5.x']))
    expect(topologicalSort(idx)).toEqual({ ordered: ['2'], cycles: [], missing: [] })
  })

  it('mixed exact + wildcard deps deduplicate', () => {
    const idx = index(task('1.1'), task('1.2'), task('2'), task('3', 'pending', ['1.1', '1.x']))
    expect(topologicalSort(idx).ordered).toEqual(['1.1', '1.2', '2', '3'])
  })

  it('stable across repeated runs (Go TestTopologicalSort_WildcardStability)', () => {
    const idx = index(task('1.1'), task('1.2'), task('1.3'), task('2', 'pending', ['1.x']))
    const first = JSON.stringify(topologicalSort(idx))
    for (let i = 0; i < 4; i++) expect(JSON.stringify(topologicalSort(idx))).toBe(first)
  })
})

describe('task 1.2 — dangling blockers stay verbatim (AC-4, findDanglingBlockers precedent)', () => {
  const danglingUrl = new URL('real-index-m3-dangling.json', fixturesUrl)

  it('missing markers name the dangling key; the dependency field is not rewritten', () => {
    const snapshot = JSON.parse(readFileSync(danglingUrl, 'utf8')) as {
      tasks: Record<string, { dependencies?: readonly string[] }>
    }
    const idx = parseTaskIndexSnapshot(snapshot)
    const probe = idx.byId('6.9')
    expect(probe?.dependencies).toEqual(['9.9', '5.gate']) // 原词保留
    expect(topologicalSort(idx).missing).toEqual(['9.9'])
    expect(getUnmetDeps(idx, '6.9', probe?.dependencies)).toEqual(['9.9', '5.gate'])
    expect(checkTransitionDeps(idx, '6.9')).toEqual({ unmet: ['9.9', '5.gate'], error: null })
  })

  it('inputs are never mutated by any probe (no side effects)', () => {
    const before = readFileSync(danglingUrl, 'utf8')
    const idx = parseTaskIndexSnapshot(JSON.parse(before))
    topologicalSort(idx)
    for (const t of idx.tasksMap().values()) getUnmetDeps(idx, t.id, t.dependencies)
    checkTransitionDeps(idx, '6.9')
    expect(JSON.stringify(idx.tasksMap())).toBe(
      JSON.stringify(parseTaskIndexSnapshot(JSON.parse(before)).tasksMap()),
    )
  })
})

describe('task 1.2 parity — Go baseline zero diff (forge-cli pkg/task)', () => {
  it('baseline shape: 18 dep cases, 16 topo cases, 4 real indexes', () => {
    expect(baseline.depCases).toHaveLength(18)
    expect(baseline.toposortCases).toHaveLength(16)
    expect(baseline.realIndexes.map(r => r.name)).toEqual(['m1', 'm2', 'm3', 'm3-dangling'])
  })

  it('dep cases: checkTransitionDeps + getUnmetDeps match Go per case', () => {
    const failures: string[] = []
    for (const c of corpus.depCases) {
      const want = baseline.depCases.find(b => b.name === c.name)
      if (want === undefined) throw new Error(`baseline missing dep case: ${c.name}`)
      const idx = corpusIndex(c.tasks)
      const got = checkTransitionDeps(idx, c.target)
      if (JSON.stringify(sorted(got.unmet)) !== JSON.stringify(sorted(want.checkDeps?.unmet))) {
        failures.push(`${c.name} checkDeps.unmet: ${JSON.stringify(got.unmet)} != ${JSON.stringify(want.checkDeps?.unmet)}`)
      }
      if ((got.error ?? '') !== (want.checkDeps?.error ?? '')) {
        failures.push(`${c.name} checkDeps.error: ${got.error} != ${want.checkDeps?.error}`)
      }
      const deps = c.rawDeps ?? idx.byId(c.target)?.dependencies ?? []
      const gotUnmet = getUnmetDeps(idx, c.target, deps)
      if (JSON.stringify(sorted(gotUnmet)) !== JSON.stringify(sorted(want.unmet))) {
        failures.push(`${c.name} getUnmetDeps: ${JSON.stringify(gotUnmet)} != ${JSON.stringify(want.unmet)}`)
      }
    }
    expect(failures, failures.join('\n')).toEqual([])
  })

  it('toposort cases: ordered/cycles/missing match Go exactly (strict order)', () => {
    const failures: string[] = []
    for (const c of corpus.toposortCases) {
      const want = baseline.toposortCases.find(b => b.name === c.name)
      if (want === undefined) throw new Error(`baseline missing topo case: ${c.name}`)
      const got = topologicalSort(corpusIndex(c.tasks))
      if (JSON.stringify(got.ordered) !== JSON.stringify(want.ordered ?? [])) {
        failures.push(`${c.name} ordered: ${JSON.stringify(got.ordered)} != ${JSON.stringify(want.ordered)}`)
      }
      if (JSON.stringify(got.cycles) !== JSON.stringify(want.cycles ?? [])) {
        failures.push(`${c.name} cycles: ${JSON.stringify(got.cycles)} != ${JSON.stringify(want.cycles)}`)
      }
      if (JSON.stringify(got.missing) !== JSON.stringify(want.missing ?? [])) {
        failures.push(`${c.name} missing: ${JSON.stringify(got.missing)} != ${JSON.stringify(want.missing)}`)
      }
    }
    expect(failures, failures.join('\n')).toEqual([])
  })

  it('real index corpora (phase keys, T- tasks, slug keys, dangling blocker): zero diff', () => {
    const failures: string[] = []
    for (const want of baseline.realIndexes) {
      const snapshot = JSON.parse(readFileSync(new URL(`real-index-${want.name}.json`, fixturesUrl), 'utf8'))
      const idx = parseTaskIndexSnapshot(snapshot)
      const got = topologicalSort(idx)
      if (JSON.stringify(normalizeTies(got.ordered)) !== JSON.stringify(normalizeTies(want.ordered))) {
        failures.push(`${want.name} ordered head: ${JSON.stringify(got.ordered.slice(0, 5))} != ${JSON.stringify((want.ordered ?? []).slice(0, 5))}`)
      }
      if (JSON.stringify(normalizeTies(got.cycles)) !== JSON.stringify(normalizeTies(want.cycles))) failures.push(`${want.name} cycles differ`)
      if (JSON.stringify(normalizeTies(got.missing)) !== JSON.stringify(normalizeTies(want.missing))) failures.push(`${want.name} missing differ`)
      for (const [taskId, wantUnmet] of Object.entries(want.unmetByTask)) {
        const gotUnmet = getUnmetDeps(idx, taskId, idx.byId(taskId)?.dependencies)
        if (JSON.stringify(sorted(gotUnmet)) !== JSON.stringify(sorted(wantUnmet))) {
          failures.push(`${want.name} ${taskId} unmet: ${JSON.stringify(gotUnmet)} != ${JSON.stringify(wantUnmet)}`)
        }
      }
      for (const [taskId, wantCheck] of Object.entries(want.checkDepsByTask)) {
        const gotCheck = checkTransitionDeps(idx, taskId)
        if (JSON.stringify(sorted(gotCheck.unmet)) !== JSON.stringify(sorted(wantCheck.unmet))) {
          failures.push(`${want.name} ${taskId} checkDeps.unmet differs`)
        }
        if ((gotCheck.error ?? '') !== (wantCheck.error ?? '')) failures.push(`${want.name} ${taskId} checkDeps.error differs`)
      }
    }
    expect(failures, failures.join('\n')).toEqual([])
  })
})
