import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { ALL_STATUSES } from '../src/main/workbench/tasks/model.ts'
import {
  ROLES,
  TRANSITION_TABLE,
  TransitionError,
  validateTransition,
  type TransitionRole,
} from '../src/main/workbench/tasks/statemachine.ts'

// Task 1.2 (M3) — 7-state task statemachine, TS port of forge-cli
// pkg/task/statemachine.go. The port authority is the Go source (task Hard
// Rules: 逐函数核对,行为差异一律以 Go 为准); the behavioral baseline in
// __fixtures__/baseline.json was generated by scripts/tasks-parity-gen
// against forge-cli @644321da. Parity = zero difference per edge, including
// the formatted rejection message.
//
// SPEC note: AC-2's parenthetical "(completed/skipped/rejected 视为满足)"
// contradicts the Go authority (deps.go satisfiedStatuses = completed/skipped
// only; Go test TestCheckTransitionDeps_RejectedDoesNotSatisfy) — Hard Rule
// #1 wins; see workbench-tasks-deps.spec.ts for the rejected case.

interface BaselineTransition {
  readonly from: string
  readonly to: string
  readonly role: string
  readonly allowed: boolean
  readonly error: { readonly message: string; readonly guardMsg: string } | null
}

interface Baseline {
  readonly forgeCliCommit: string
  readonly transitions: readonly BaselineTransition[]
}

const baseline: Baseline = JSON.parse(
  readFileSync(new URL('../src/main/workbench/tasks/__fixtures__/baseline.json', import.meta.url), 'utf8'),
)

describe('task 1.2 statemachine — full 7×7×5 matrix parity vs Go baseline', () => {
  it('baseline covers all 245 edges (7 states × 7 states × 5 roles)', () => {
    expect(baseline.transitions).toHaveLength(7 * 7 * ROLES.length)
    expect(ALL_STATUSES).toHaveLength(7)
    expect(ROLES).toHaveLength(5)
  })

  it('every edge matches the Go verdict and rejection message exactly', () => {
    const failures: string[] = []
    for (const entry of baseline.transitions) {
      const label = `${entry.from} -> ${entry.to} (role=${entry.role})`
      const err = validateTransition(entry.from, entry.to, entry.role as TransitionRole)
      if (entry.allowed) {
        if (err !== null) failures.push(`${label}: expected allowed, got "${err.message}"`)
        continue
      }
      if (err === null) {
        failures.push(`${label}: expected rejection, got allowed`)
        continue
      }
      if (err.message !== entry.error?.message) failures.push(`${label}: message "${err.message}" != "${entry.error?.message}"`)
      if (err.guardMsg !== entry.error?.guardMsg) failures.push(`${label}: guardMsg "${err.guardMsg}" != "${entry.error?.guardMsg}"`)
    }
    expect(failures, failures.join('\n')).toEqual([])
  })

  it('TRANSITION_TABLE stays at the ported Go rule count (first-match-wins order)', () => {
    expect(TRANSITION_TABLE).toHaveLength(23)
  })
})

describe('task 1.2 statemachine — terminal state protection', () => {
  it('completed is irreversible: every target × role is rejected', () => {
    for (const to of ALL_STATUSES) {
      for (const role of ROLES) {
        expect(validateTransition('completed', to, role), `completed -> ${to} (${role})`).not.toBeNull()
      }
    }
  })

  it('rejected and skipped reopen to pending only (single legal escape edge each)', () => {
    for (const from of ['rejected', 'skipped'] as const) {
      for (const to of ALL_STATUSES) {
        for (const role of ROLES) {
          const expectedAllowed = to === 'pending' && role === 'reopen'
          const err = validateTransition(from, to, role)
          expect(err === null, `${from} -> ${to} (${role})`).toBe(expectedAllowed)
        }
      }
    }
  })

  it('only submit reaches completed, and suspended must resume first', () => {
    for (const from of ALL_STATUSES) {
      // terminal states are covered above (no escape except reopen -> pending)
      if (from === 'completed' || from === 'rejected' || from === 'skipped') continue
      for (const role of ROLES) {
        const expectedAllowed = role === 'submit' && from !== 'suspended'
        const err = validateTransition(from, 'completed', role)
        expect(err === null, `${from} -> completed (${role})`).toBe(expectedAllowed)
      }
    }
    expect(validateTransition('suspended', 'completed', 'submit')?.guardMsg).toBe('use forge task transition to resume task first')
  })
})

describe('task 1.2 statemachine — suspended (manual hold)', () => {
  it('entering suspended is manual-only from non-terminal states', () => {
    expect(validateTransition('pending', 'suspended', 'manual')).toBeNull()
    expect(validateTransition('in_progress', 'suspended', 'manual')).toBeNull()
    expect(validateTransition('blocked', 'suspended', 'manual')).toBeNull()
    expect(validateTransition('pending', 'suspended', 'auto')).not.toBeNull()
    expect(validateTransition('in_progress', 'suspended', 'submit')).not.toBeNull()
    expect(validateTransition('rejected', 'suspended', 'manual')).not.toBeNull() // terminal
  })

  it('manual resume and manual terminal decisions from suspended', () => {
    expect(validateTransition('suspended', 'pending', 'manual')).toBeNull()
    expect(validateTransition('suspended', 'in_progress', 'manual')).toBeNull()
    expect(validateTransition('suspended', 'skipped', 'manual')).toBeNull()
    expect(validateTransition('suspended', 'rejected', 'manual')).toBeNull()
  })

  it('system transitions from suspended are blocked (must resume first)', () => {
    expect(validateTransition('suspended', 'blocked', 'auto')).not.toBeNull()
    expect(validateTransition('suspended', 'blocked', 'submit')).not.toBeNull()
    expect(validateTransition('suspended', 'pending', 'reopen')).not.toBeNull()
    expect(validateTransition('suspended', 'suspended', 'manual')).toBeNull() // same-state no-op
  })
})

describe('task 1.2 statemachine — blocked and general edges', () => {
  it('blocked escapes demand dependency check unless manual', () => {
    expect(validateTransition('blocked', 'pending', 'claim')?.guardMsg).toBe('dependencies must be checked first')
    expect(validateTransition('blocked', 'in_progress', 'submit')?.guardMsg).toBe('dependencies must be checked first')
    expect(validateTransition('blocked', 'pending', 'manual')).toBeNull()
    expect(validateTransition('blocked', 'in_progress', 'manual')).toBeNull()
  })

  it('pending -> blocked is always allowed (any role)', () => {
    for (const role of ROLES) {
      expect(validateTransition('pending', 'blocked', role), `pending -> blocked (${role})`).toBeNull()
    }
  })

  it('submit can downgrade in_progress -> blocked; auto falls through to the open rule', () => {
    expect(validateTransition('in_progress', 'blocked', 'submit')).toBeNull()
    expect(validateTransition('in_progress', 'blocked', 'auto')).toBeNull()
  })

  it('same-state transitions are no-ops except reopen (suspended: manual only)', () => {
    for (const state of ['pending', 'in_progress', 'blocked', 'suspended'] as const) {
      for (const role of ROLES) {
        const err = validateTransition(state, state, role)
        // suspended -> suspended via non-manual hits the "* -> suspended" guard first
        const expectedAllowed = state === 'suspended' ? role === 'manual' : role !== 'reopen'
        expect(err === null, `${state} -> ${state} (${role})`).toBe(expectedAllowed)
      }
    }
  })
})

describe('task 1.2 statemachine — TransitionError shape', () => {
  it('mirrors the Go TransitionError fields and message formatting', () => {
    const err = validateTransition('completed', 'pending', 'submit')
    expect(err).toBeInstanceOf(TransitionError)
    expect(err?.from).toBe('completed')
    expect(err?.to).toBe('pending')
    expect(err?.role).toBe('submit')
    expect(err?.guardMsg).toBe('task already completed, create a subtask if re-work needed')
    expect(err?.message).toBe(
      'invalid transition completed -> pending (role=submit): task already completed, create a subtask if re-work needed',
    )
    expect(err?.name).toBe('TransitionError')
  })
})
