// ipc/ barrel（定位：基础——{url,injections} 通道 + forge:* 注册与 allowlist + RPC 信封机制与注册行 + knowledge 绑定表维护）。
export * from './bindings.js'
export * from './boot-channel.js'
export * from './directory-picker-channel.js'
export * from './docs-rpc.js'
export * from './features-rpc.js'
export * from './forge-channels.js'
export * from './fs-rpc.js'
export * from './knowledge-rpc.js'
export * from './m2-wiring.js'
export * from './preload-api.js'
export * from './projects-rpc.js'
export * from './proposals-rpc.js'
export * from './rpc-envelope.js'
export * from './settings-rpc.js'
export * from './tasks-rpc.js'
export * from './test-bridge.js'
